#   Your global data folder is controlled by the dir.data configuration option. 
#  All *.json and module.exports values from *.js files in this directory will 
#  be added into a global data object available to all templates.

#  This file can be accessed using: {{ site.title }}

title: "Isdoman" # Appears after the title Page eg. Title - Web Starter
description: "My description" 
url: "https://isdoman.net/FORTEST/"
# url: "http://localhost:8080"

author: "Nikhil R"
meta_data: 
 website: "nikhilr.me"
